### ISSUE TITLE
DHCP Issue - 169.x.x.x address

### ISSUE THREAD

**Issue by lukewis** [jasbur/RaspiWiFi#17]
Been having an issue (seen on Pi Zero W and Pi B+) where the pi fails to assign itself an ip address.  It broadcasts the RaspiWifi network, but it lists the ip address as a 169.x.x.x address instead of the desired 10.0.0.1.  The Pi B+ eventually seemed to get an ip address (after many reboots), but my Pi Zero seems stuck in this state.  Any thoughts or items to check?

**Comment by lukewis** [comment]
I'm thinking this is a bug in the Raspian GUI......when I hover over the wifi indicator in the status bar, it shows the 169 address, but I can indeed connect to 10.0.0.1.  I also see that the 10.0.0.1 address is set statically in /etc/network/interfaces, so it's not being assigned by DHCP.

**Comment by jasbur** [comment]
I just released version 1.5 that should fix this issue.
