### ISSUE TITLE
Change Setup Port

### ISSUE THREAD

**Issue by scottrpaterson** [jasbur/RaspiWiFi#28]
This is a great project! Thank you for making this!

I would like to point a hosts file address for 10.0.0.1:9191 to an easier to type address for setup. So that when someone visits setup.local it pulls up the setup page. However hosts files can't include a port in the address. So ideally I need to remove the port.

In aphost_bootstrapper.template was the only reference I found to 9191 in the code, however if I remove 9191 it breaks. 

Is it possible to run setup without a port number?

**Comment by jasbur** [comment]
Rails will actually start the server on port 3000 by default so removing the `-p` switch probably wont work for you. I think you'll probably want the server to be running on the default HTTP port (80) to have it just work in a browser.

You're looking in the right place for that. Just change:

`su -c "cd [[project_dir]]/Configuration\ App/ && rails s -b 0.0.0.0 -e production -p 9191 -d"`

to

`su -c "cd [[project_dir]]/Configuration\ App/ && rails s -b 0.0.0.0 -e production -p 80 -d"`

and that should take care of it.
