### ISSUE TITLE
CSS Styling needed on Wifi configuration page

### ISSUE THREAD

**Issue by jasbur** [jasbur/RaspiWiFi#3]

**Comment by FaizB** [comment]
which file can i change to improve the captive portal page, To add some css

**Comment by jasbur** [comment]
The HTML can be found in:

Configuration App/app/views/main/index.html.erb

And the CSS can be found in:

Configuration App/app/assets/stylesheets/application.css

**Comment by jasbur** [comment]
Also, you can start a temporary web server by navigating to the "Configuration App" directory in a console and issuing:

sudo rails s

If you'd like to access from another decide on your network (like your phone) you can issue:

sudo rails s -b 0.0.0.0

**Comment by jasbur** [comment]
@tiito78 mad some great styling and I fixed a bug causing styling to not display at all.
