### ISSUE TITLE
How to Change Access Point Name

### ISSUE THREAD

**Issue by rajkiranjeet** [jasbur/RaspiWiFi#31]
Hi
anyway to change access point Name

**Comment by jasbur** [comment]
Yes, Just change the string variable on this line before running the `initial_setup.py`

https://github.com/jasbur/RaspiWiFi/blob/73bd5f2af529b64cd06ecca773e0c0e26667a648/Reset%20Device/reset.py.template#L13

Change "RaspiWiFi Setup " to whatever you want. The last four of your Raspberry Pi's serial number will still be appended to the end,
