### ISSUE TITLE
HTML layout no longer re-sizing properly on mobile devices

### ISSUE THREAD

**Issue by jasbur** [jasbur/RaspiWiFi#36]
Since I ported the Configuration App over to Flask the HTML layout doesn't seem to be responsive like it was under the old Ruby on Rails implementation.

@tiito78 Since you were the contributor for this portion of the project I was wondering if you could take a look at it. I tried, but I can't seem to spot the cause.

**Comment by jasbur** [comment]
I forgot to mention that this is happening in the [flask_config_conversion](https://github.com/jasbur/RaspiWiFi/tree/flask_config_conversion) branch.

**Comment by tiito78** [comment]
@jasbur I can have a look on this later on today. I will get back to you!

**Comment by jasbur** [comment]
I don't see the CSS file... Forgot to attach it maybe?

**Comment by tiito78** [comment]
pls check again, otherwise download from here:
-- 
Med vänliga hälsningar,
Best regards,

Felipe Gomez Morales
Webdesigner

Tlf.: +46 (0)702 97 00 45
www.felipe.se




11 juni 2018 20:24:29 +02:00, skrev Jason Burgett <notifications@github.com>:

**Comment by jasbur** [comment]
I really don't see the CSS file, or even the link you gave me in your second message. I've attached a screenshot of what I see. You could also try to issue a pull request.

![screenshot from 2018-06-11 14-00-17](https://user-images.githubusercontent.com/3278428/41251591-fe734d28-6d7f-11e8-801c-599363c437d1.png)

**Comment by tiito78** [comment]
I will try pull request. On my way home. Give me 30 minDen 11 juni 2018 21:02 skrev Jason Burgett <notifications@github.com>:I really don't see the CSS file, or even the link you gave me in your second message. I've attached a screenshot of what I see. You could also try to issue a pull request.

**Comment by jasbur** [comment]
No rush, I'm heading out on appointments for the rest of the day anyway. I'll keep an eye out for it. Thanks.

**Comment by tiito78** [comment]
hi Jason!


pls have a look now at git.....
-- 
Med vänliga hälsningar,
Best regards,

Felipe Gomez Morales
Webdesigner

Tlf.: +46 (0)702 97 00 45
www.felipe.se




11 juni 2018 21:15:55 +02:00, skrev Jason Burgett <notifications@github.com>:

**Comment by jasbur** [comment]
@tiito78 Fixed this problem. It was primarily related to a missing `meta` tag in the `layout.html` He also made some tweaks to the CSS layout. The fixes have been added to the [flask_config_conversion](https://github.com/jasbur/RaspiWiFi/tree/flask_config_conversion) branch and will be incorporated into `v1.8`
