### ISSUE TITLE
Not working for me

### ISSUE THREAD

**Issue by hbattat** [jasbur/RaspiWiFi#40]
I tried using the script to install, and I was not able to see an AP. Then I started fresh with your IMG file, still no luck, am I missing something?
This is on a RPI B+ and  with a Realtek 8188EUS Wifi dongle

Thanks for your help, this is a great solution (when it works for me :) )

**Comment by jasbur** [comment]
I've only tested the software with Raspberry Pi 3, Raspberry Pi zero W, and a Raspberry Pi B+ using an Edimax Wi-Fi adapter. My guess is that the chipset your Realtek adapter is using may not be compatible with hostapd, which is used to generate the access point.

It's possible that the current configuration for hostapd is a little too specific. Try deleting this line:

`driver=nl80211`

From `/etc/hostapd/hostapd.conf` and `/usr/lib/raspiwifi/reset_device/static_files/hostapd.conf` After that reboot the Pi back into configuration mode and see if it works.

**Comment by jasbur** [comment]
Did you end up trying this fix out? Did it work for you?

**Comment by hbattat** [comment]
It was my USB wifi dongle, It does seem like it is supported by hostapd
