### ISSUE TITLE
AP SSID not showing after Reset

### ISSUE THREAD

**Issue by chalamministries** [jasbur/RaspiWiFi#45]
I did a Manual_reset.py but now the AP doesnt show. 
I manually edited /etc/default/hostapd to point to the conf file but I shouldn't have to do that. What could be wrong?

**Comment by jasbur** [comment]
I'm having trouble reproducing your issue.

I flashed an SD Card with the latest Raspbian version (2018-06-27-raspbian-stretch-lite) and ran the RapiWiFi install script. After I used the Configuration Page to connect to my local WiFi connection I logged in with SSH to the Pi and ran:

`sudo python3 /usr/lib/raspiwifi/reset_device/manual_reset.py`

After a reboot my Pi worked correctly and broadcasted the proper AP which I was able to connect to successfully. Can you think of anything that might be different about your situation that might makes this reproducible on my end?
