### ISSUE TITLE
Ended up with rebooting raspberry again and again. (Raspberry pi 3)

### ISSUE THREAD

**Issue by mjdileep** [jasbur/RaspiWiFi#5]
Raspberry is continuously rebooting after initial setup.

**Comment by mjdileep** [comment]
Adding a delay after `fi` in files **RaspiWiFi/Reset Device/static_files/rc.local.apclient** and **RaspiWiFi/Reset Device/static_files/rc.local.apclient.template** did solve the issue.
see: 
![image](https://user-images.githubusercontent.com/6938724/29565892-74acc0e8-8765-11e7-9420-c373285e4d4a.png)

**Comment by jasbur** [comment]
Thanks for the info. I'll try it with a shorter delay and add it to the project.
