### ISSUE TITLE
Invalid DNS from DHCP Client when on client mode

### ISSUE THREAD

**Issue by emsilva** [jasbur/RaspiWiFi#57]
My DNS is defaulting to 127.0.0.1, instead of using the DNS provided by the DHCP client on my network. I tried different routers and getting the same results. I'm using the latest img release.

cat /etc/resolv.conf
```
# Generated by resolvconf
nameserver 127.0.0.1
```

**Comment by emsilva** [comment]
Stupid that the 127.0.0.1 is how things works... I'm still having DNS problems, but I'll find out better what is the problem before I post again.

**Comment by maxpage92** [comment]
Did you ever figure it out? I'm having the same issue where resolv.conf is 127.0.0.1 and it's causing some networking issues. I have my pi running as a kiosk on boot and for the first 10 seconds after chromium loads it has a dns error. Then it loads correctly. Ping works well beforehand so it must be this. Any solutions?
