### ISSUE TITLE
Doesn't work on Raspberry Pi 3 Model B

### ISSUE THREAD

**Issue by proudloyaltier** [jasbur/RaspiWiFi#64]
The connection page never loads and does not open config mode on startup

**Comment by DustinDobernig** [comment]
Experiencing same issue

**Comment by jasbur** [comment]
Can either of you try commenting out or removing `Line 2` (`driver=nl80211`) in `libs/reset_device/static_files/hostapd.conf` (or in `/etc/hostapd/hostapd.conf` if you've already run the `initial_setup.py`) to see if that makes a difference?

**Comment by proudloyaltier** [comment]
I tried reinstalling RaspiWiFi, and it worked perfectly fine!!  I tried it on 2 other Pi 3B and it worked first try on one and second try on the other

**Comment by jasbur** [comment]
I just tested on a Raspberry Pi 3 B+ with no issues. I'll close this for now and chalk it up to fluke until we have more consistent information to work from.
