### ISSUE TITLE
RPi Zero W issue ( unable to connect to the AP{RaspiWifi} )

### ISSUE THREAD

**Issue by akshaykulkarni46** [jasbur/RaspiWiFi#7]
I tried this on RPi Zero W and I was able to create the AP {RaspiWifi} but unfortunately i was unable to connect to that AP using mobile or PC

**Comment by jasbur** [comment]
Can you provide any more information, such as which devices you tried to connect with or any errors messages you received?

**Comment by akshaykulkarni46** [comment]
Hello Sir , 
I tried this on Raspberry pi Zero W and while installing Rails gems using sudo bundle install I had some issues . 
Thanks & Regards
- Akshay Kulkarni
  IQ Root Technologies ,
  Bengaluru  -560056

---- On Thu, 31 Aug 2017 22:20:55 +0530 notifications@github.com wrote ----

Can you provide any more information, such as which devices you tried to connect with or any errors messages you received?

**Comment by adilberrada** [comment]
Hi thank you for your code ! I am having the same issue as @akshaykulkarni46. I am unable to connect to the AP using my mobile or PC. I am using a rpi3 and tried to connect with my mac and iPhone.

Any idea ?
Thanks a lot

**Comment by jasbur** [comment]
@adilberrada Recent updates seem to have resolved the issue for @akshaykulkarni46 Have you had a chance to try a more recent version of the code?
