### ISSUE TITLE
How to fully remove this module from the system

### ISSUE THREAD

**Issue by murugesh-smp** [jasbur/RaspiWiFi#70]
Hi team, great work. it's working fine. I would like to completely remove this from the system. I couldn't able to remove it. can you or anyone please provide me the steps for complete removal of this. Thanks

**Comment by jasbur** [comment]
I just added an Uninstaller to the project. If you update your repository or re-clone it you can run the Uninstaller like this:

`sudo python3 libs/uninstall.py`

Install from now on can always access it from `/usr/lib/raspiwifi/uninstall.py` as well.
