### ISSUE TITLE
Dynamic Access point name

### ISSUE THREAD

**Issue by arjunmenon** [jasbur/RaspiWiFi#8]
Hey
Is it possible to have a dynamic SSID name from `RaspiWiFi Setup` to `RaspiWiFi Setup@10.0.0.1`, or whatever the ip-address is?

This will make it easier for a person to know exactly where to navigate.

**Comment by jasbur** [comment]
Yes, you can change the broadcast SSID by editing the line:

`ssid=RaspiWiFi-Setup`

in:

`RaspiWiFi\Reset Device\static_files\hostapd.conf`

You can also change the title on the setup page by editing the line:

`<title>WiFiSetupUi</title>`

in:

`RaspiWiFi\Configuration App\app\views\layouts\application.html.erb`
